export default function Head() {
  return (
    <>
      <title>Weather App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Circle-icons-weather.svg/2048px-Circle-icons-weather.svg.png"
      />
    </>
  );
}
